name: Build and deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sncf-on-time:$GITHUB_SHA

    - name: Tag the Docker image
      run: docker tag sncf-on-time:$GITHUB_SHA europe-west9-docker.pkg.dev/ensai-2023-373710/zixuan/sncf-on-time:$GITHUB_SHA

    - name: Auth on GCP
      uses: docker/login-action@v2
      with:
        registry: europe-west9-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Push the Docker tagged image
      run: docker push europe-west9-docker.pkg.dev/ensai-2023-373710/zixuan/sncf-on-time:$GITHUB_SHA
        
        
        
